## Markov Processes

### Markov Chain - Continuing

![Markov Chain](./images/mchain.png "Markov Chain")

In [2]:
import numpy as np

In [3]:
# MC with no end

# import numpy library to do vector algebra
import numpy as np

# define transition matrix
P = np.array([[0.3, 0.7], [0.2, 0.8]])
print("Trnasition Matrix:\n", P)

# define any starting solution to state probabilities
# Here we assume equal probabilities for all the states
S = np.array([0.5, 0.5])

# run through 10 iterations to calculate steady state
# transition probabilities
for i in range(10):
    S = np.dot(S, P)
    print("\nIter {0}. Probability vector S = {1}".format(i, S))


print("\nFinal Vector S={0}".format(S))

Trnasition Matrix:
 [[0.3 0.7]
 [0.2 0.8]]

Iter 0. Probability vector S = [0.25 0.75]

Iter 1. Probability vector S = [0.225 0.775]

Iter 2. Probability vector S = [0.2225 0.7775]

Iter 3. Probability vector S = [0.22225 0.77775]

Iter 4. Probability vector S = [0.222225 0.777775]

Iter 5. Probability vector S = [0.2222225 0.7777775]

Iter 6. Probability vector S = [0.22222225 0.77777775]

Iter 7. Probability vector S = [0.22222223 0.77777778]

Iter 8. Probability vector S = [0.22222222 0.77777778]

Iter 9. Probability vector S = [0.22222222 0.77777778]

Final Vector S=[0.22222222 0.77777778]


### Markov Chain - Episodic


![Markov Chain Episodic](./images/mc_episodic.png "Markov Chain Episodic")

In [4]:
# MC Episodic

# import numpy library to do vector algebra
import numpy as np

# define transition matrix
P = np.array([
    [0.3, 0.5, 0.2, 0.0],
    [0.1, 0.9, 0.0, 0.0],
    [0.4, 0, 0, 0.6],
    [0, 0, 0, 1]
])

print("Trnasition Matrix:\n", P)

# define any starting solution to state probabilities
# Here we assume equal probabilities for all the states
S = np.array([1, 0, 0, 0])

# run through 10 iterations to calculate steady state
# transition probabilities
for i in range(1000):
    S = np.dot(S, P)
    # print("\nIter {0}. Probability vector S = {1}".format(i, S))


print("\nFinal Vector S={0}".format(S))

Trnasition Matrix:
 [[0.3 0.5 0.2 0. ]
 [0.1 0.9 0.  0. ]
 [0.4 0.  0.  0.6]
 [0.  0.  0.  1. ]]

Final Vector S=[4.73405766e-09 2.84857504e-08 9.63092427e-10 9.99999966e-01]


### Markov Reward Process - Continuing

![Markov Reward Process](./images/mrp_continuing.png "Markov Reward Process")

In [5]:
# MRP Continuing

# import numpy library to do vector algebra
import numpy as np

# define transition matrix
P = np.array([[0.3, 0.7], [0.2, 0.8]])
print("Trnasition Matrix:\n", P)

# define any starting solution to state probabilities
# Here we assume equal probabilities for all the states
S = np.array([0.5, 0.5])

# run through 10 iterations to calculate steady state
# transition probabilities
for i in range(10):
    S = np.dot(S, P)
    print("\nIter {0}. Probability vector S = {1}".format(i, S))

# steady state S
print("\nFinal Vector S={0}".format(S))

Trnasition Matrix:
 [[0.3 0.7]
 [0.2 0.8]]

Iter 0. Probability vector S = [0.25 0.75]

Iter 1. Probability vector S = [0.225 0.775]

Iter 2. Probability vector S = [0.2225 0.7775]

Iter 3. Probability vector S = [0.22225 0.77775]

Iter 4. Probability vector S = [0.222225 0.777775]

Iter 5. Probability vector S = [0.2222225 0.7777775]

Iter 6. Probability vector S = [0.22222225 0.77777775]

Iter 7. Probability vector S = [0.22222223 0.77777778]

Iter 8. Probability vector S = [0.22222222 0.77777778]

Iter 9. Probability vector S = [0.22222222 0.77777778]

Final Vector S=[0.22222222 0.77777778]
